insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Arbalète légère','Petite Arbalete','1','8','-1','70','l''arbalète ressemble à un arc posé horizontalement sur un fût en bois ou en métal. On la préfère généralement à l''arc car elle est bien plus simple d''utilisation.','6',0,'50','Dexterite','Petite Arbalete',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Arc court','Arc Court','2','6','50','60','l''arc court fait environ 1,50 mètre de long non courbé. C''est le premier à avoir été mis au point et il a su conserver son efficacité au fil du temps.','2',0,'40','Dexterite','Arc Court',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Arc droit','Arc Court','1','4','50','30','l''arc droit, ou le Longbow est constitué d''une simple branche d''arbre ou de plusieurs matériaux assemblés et d''une corde en matériaux naturels','4',0,'30','Dexterite','Arc Court',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Arbalète lourde','Grande Arbalete','2','10','-1','100','l''arbalète lourde est la plus grosse arme de sa catégorie et son efficacité fait que beaucoup de miliciens la choisissent comme arme de prédilection. Elle est plus redoutable que l''arbalète légère, mais aussi bien plus encombrante.','9',0,'100','Dexterite','Grande Arbalete',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Arc composite','Arc Long','10','15','-1','200','Un Arc composite est constitué de 3 couches de matériaux différents pour le rendre plus puissant, il peut mesurer jusqu''à 2 mètres de long…','4',0,'50','Dexterite','Arc Long',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Arc long','Arc Long','2','8','-1','150','l''arc long est une amélioration de l''arc court, qui permet de tirer des flèches plus loin, en leur conférant une plus grande force de pénétration. Il est généralement adapté à la taille de son utilisateur et peut dépasser 1,80 mètre de long.','3',0,'100','Dexterite','Arc Long',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Sceptre magique','Artefact Majeur','15','25','-1','300','Le sceptre est un objet magique potentiel. Pouvoirs et effets varient grandement d''un modèle à l''autre.','2',0,'200','Sagesse','Artefact Majeur',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Baguette magique','Artefact Mineur','10','15','-1','100','La baguette est un objet magique potentiel. Pouvoirs et effets varient grandement d''un modèle à l''autre.','1',0,'50','Sagesse','Artefact Mineur',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Bâton magique','Artefact Mineur','15','20','-1','200','Le bâton est un objet magique potentiel. Pouvoirs et effets varient grandement d''un modèle à l''autre.','4',0,'100','Sagesse','Artefact Mineur',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Hache d''armes','Hache Courte','4','8','50','20','La hache d''armes se résume à une lame tranchante montée sur un manche long d''un mètre à un mètre vingt','7',0,'-1','Dexterite','Hache Courte',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Hache de lancer','Hache Courte','1','6','-1','4','La hache de lancer n''a plus grand-chose en commun avec la hachette des cours de ferme qui lui a donné naissance. Parfaitement équilibrée pour être lancée, elle offre une grande précision mais sa solidité en pâtit.','1',0,'1','Dexterite','Hache Courte',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Hachette','Hache Courte','1','6','10','12','La hachette est plus petite que les autres haches de combat. Bien souvent, on s''en sert comme deuxième arme, dans la main non directrice.','5',0,'-1','Dexterite','Hache Courte',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Double hache','Hache Longue','12','16','80','120','On ne peut nier que la race Orque a eu un effet important sur l''art de la guerre. Le concept de la hache double vient d''une philosophie aussi simple qu''imparable : ''Si une lame bien, deux lames encore plus mieux !''','25',0,'-1','Force','Hache Longue',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Faux de combat','Hache Longue','2','4','15','36','Bien qu''elle ressemble bien évidemment à l''ustensile agricole dont elle est dérivée, la faux de guerre a été renforcée afin de ne pas se briser au premier combat.','12',0,'-1','Force','Hache Longue',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Grande hache','Hache Longue','6','12','70','40','La grande hache est l''arme de prédilection des barbares, ainsi que la plus terrible des armes dérivées de la hache de bûcheron. Ses deux lames sont bien plus efficaces pour trancher les adversaires en deux que pour couper les arbres.','20',0,'-1','Force','Hache Longue',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Hallebarde','Hache Longue','4','10','25','20','La hallebarde est l''arme d''hast la plus courante qui soit. On pourrait la définir en disant qu''elle se trouve à mi-chemin de la lance et de la hache','15',0,'-1','Force','Hache Longue',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Dague','Lame Courte','1','4','30','4','Arme de base mais très polyvalente, la dague est dotée d''une lame à double tranchant faisant généralement entre 15 et 60 centimètres de long.','1',0,'-1','Dexterite','Lame Courte',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Epée courte','Lame Courte','1','6','40','20','l''épée courte est l''une des premières épées à avoir vu le jour. Elle est dotée d''une lame à double tranchant longue d''une soixantaine de centimètres','3',0,'-1','Dexterite','Lame Courte',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Kama','Lame Courte','1','6','5','4','Comme beaucoup d''armes, le kama était à l''origine un outil de ferme, et les paysans qui ont commencé à s''en servir pour se défendre n''avaient pour la plupart pas le droit de porter une épée ou une autre arme du même genre.','1',0,'-1','Dexterite','Lame Courte',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Kukri','Lame Courte','2','4','30','16','Le kukri est une lourde dague à lame courbe, dont le tranchant se trouve à l''intérieur de la courbure. Il s''agissait à l''origine d''un outil, adapté depuis à un usage guerrier ou rituel.','3',0,'-1','Dexterite','Lame Courte',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Serpe','Lame Courte','1','3','10','1','A l''origine, la serpe est un outil utilisé pour couper l''herbe ou les plants de céréales. Ce sont les paysans qui s''en servent tous les jours qui ont commencé à l''utiliser en guise d''arme, faute de mieux.','3',0,'-1','Dexterite','Lame Courte',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Cimeterre','Lame Longue à une main','2','6','35','30','Le cimeterre serait assez proche de l''épée longue et des autres armes du même type, si l''on excepte l''impressionnante courbure de sa large lame.','5',0,'-1','Force','Lame Longue',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Epée à 2 mains','Lame Longue à 2 mains','2','12','65','100','l''épée à deux mains est une arme extrêmement impressionnante. Comme son nom l''indique, la plupart des créatures ne peuvent la manier qu''à deux mains.','15',0,'-1','Force','Lame Longue',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Epée bâtarde','Lame Longue à une main','4','10','50','70','Egalement connue sous le nom d''épée ''à une main et demie'', l''épée bâtarde se situe dans une catégorie intermédiaire, entre l''épée longue et l''épée à deux mains','10',0,'-1','Force','Lame Longue',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Epée longue','Lame Longue à une main','3','8','60','30','Il en existe de nombreuses variantes, mais toutes sont dotées d''une lame qui fait entre 90 centimètres et 1,20 mètre de long.','4',0,'-1','Force','Lame Longue',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Katana','Lame Longue à une main','7','10','40','80','Le katana est la meilleure épée qui soit, puisqu''il combine grâce, beauté et redoutable efficacité d''une lame tranchante comme un rasoir.','10',0,'-1','Dexterite','Lame Longue',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Lance','Lame Longue à une main','3','8','20','20','Arme très simple, la lance est toutefois d''une efficacité redoutable. Elle consiste bien souvent en un long bout de bois taillé en pointe et équipe la plupart des milices.','3',0,'-1','Dexterite','Lame Longue',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Bâton','Masse Legere','1','6','10','2','Taillé dans un bois très résistant et parfois doté de ferrures à ses deux extrémités, le bâton est une arme que tout le monde ou presque peut apprendre à manier avec efficacité.','4',0,'-1','Dexterite','Masse Legere',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Fléau d''armes léger','Masse Legere','1','8','30','16','Dérivé d''un ustensile de ferme servant à moudre le grain, le fléau d''armes léger se compose d''une lourde tête, pointue ou non, attachée par une chaîne à un manche en bois. Il fait une soixantaine de centimètres de long.','5',0,'-1','Dexterite','Masse Legere',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Gourdin','Masse Legere','1','6','20','2','Le gourdin est l''arme la plus simpliste qui soit, puisqu''il s''agit généralement d''un simple bout de bois dur.','3',0,'-1','Dexterite','Masse Legere',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Marteau léger','Masse Legere','1','4','45','4','Le marteau léger est dérivé de l''outil du même nom. Il reste assez léger pour que l''on s''en serve lors de fouilles, par exemple, contrairement au lourd marteau de guerre.','2',0,'-1','Dexterite','Masse Legere',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Masse d''armes','Masse Legere','2','6','20','10','La masse d''armes est un dérivé du gourdin. Elle est constituée d''une tête en métal ou en pierre, fixée au bout d''un manche en bois. Le poids de la tête décuple la puissance de l''impact.','6',0,'-1','Dexterite','Masse Legere',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Fléau d''armes lourd','Masse Lourde','2','10','40','30','Dérivé d''un ustensile de ferme servant à moudre le grain, le fléau d''armes lourd se compose d''une lourde tête, pointue ou non, attachée par une chaîne à un manche en bois de 1,20 mètre de long.','20',0,'-1','Force','Masse Lourde',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Marteau de guerre','Masse Lourde','4','8','80','24','Lointain dérivé de la masse utilisée dans les travaux de construction ou de terrassement, le marteau de guerre a par la suite été tellement modifié qu''il ne peut plus aujourd''hui servir qu''au combat.','8',0,'-1','Force','Masse Lourde',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Masse d''armes double','Masse Lourde','6','8','40','80','La masse d''armes double combine la facilité d''utilisation du bâton et la puissance dévastatrice de la masse d''armes.','20',0,'-1','Force','Masse Lourde',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Morgenstern','Masse Lourde','2','8','35','16','La morgenstern est une sorte de masse avec une chaîne, semblable au fléau, pour renforcer l''impact de sa tête qui se voit dotée d''une ou plusieurs pointes augmentant son efficacité.','8',0,'-1','Force','Masse Lourde',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Fronde','Petite Fronde','1','4','-1','2','La fronde est une arme très ancienne. Bien souvent, elle se constitue d''une simple lanière en cuir ou en tissu dotée d''une partie plus évasée pour accueillir les projectiles.','1',0,'-1','Dexterite','Petite Fronde',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Shuriken','Petite Fronde','1','3','-1','5','Les shurikens sont de petits projectiles faciles à dissimuler sur sa personne. Bien qu''ils ne fassent que peu de dégâts individuellement, ils présentent l''avantage de pouvoir être lancés très rapidement.','1',0,'10','Dexterite','Petite Fronde',null);
commit;

