insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Arbalte lgre','Petite Arbalete','1','8','-1','70','l''arbalte ressemble  un arc pos horizontalement sur un ft en bois ou en mtal. On la prfre gnralement  l''arc car elle est bien plus simple d''utilisation.','6',0,'50','Dexterite','Petite Arbalete',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Arc court','Arc Court','2','6','50','60','l''arc court fait environ 1,50 mtre de long non courb. C''est le premier  avoir t mis au point et il a su conserver son efficacit au fil du temps.','2',0,'40','Dexterite','Arc Court',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Arc droit','Arc Court','1','4','50','30','l''arc droit, ou le Longbow est constitu d''une simple branche d''arbre ou de plusieurs matriaux assembls et d''une corde en matriaux naturels','4',0,'30','Dexterite','Arc Court',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Arbalte lourde','Grande Arbalete','2','10','-1','100','l''arbalte lourde est la plus grosse arme de sa catgorie et son efficacit fait que beaucoup de miliciens la choisissent comme arme de prdilection. Elle est plus redoutable que l''arbalte lgre, mais aussi bien plus encombrante.','9',0,'100','Dexterite','Grande Arbalete',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Arc composite','Arc Long','10','15','-1','200','Un Arc composite est constitu de 3 couches de matriaux diffrents pour le rendre plus puissant, il peut mesurer jusqu'' 2 mtres de long','4',0,'50','Dexterite','Arc Long',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Arc long','Arc Long','2','8','-1','150','l''arc long est une amlioration de l''arc court, qui permet de tirer des flches plus loin, en leur confrant une plus grande force de pntration. Il est gnralement adapt  la taille de son utilisateur et peut dpasser 1,80 mtre de long.','3',0,'100','Dexterite','Arc Long',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Sceptre magique','Artefact Majeur','15','25','-1','300','Le sceptre est un objet magique potentiel. Pouvoirs et effets varient grandement d''un modle  l''autre.','2',0,'200','Sagesse','Artefact Majeur',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Baguette magique','Artefact Mineur','10','15','-1','100','La baguette est un objet magique potentiel. Pouvoirs et effets varient grandement d''un modle  l''autre.','1',0,'50','Sagesse','Artefact Mineur',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Bton magique','Artefact Mineur','15','20','-1','200','Le bton est un objet magique potentiel. Pouvoirs et effets varient grandement d''un modle  l''autre.','4',0,'100','Sagesse','Artefact Mineur',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Hache d''armes','Hache Courte','4','8','50','20','La hache d''armes se rsume  une lame tranchante monte sur un manche long d''un mtre  un mtre vingt','7',0,'-1','Dexterite','Hache Courte',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Hache de lancer','Hache Courte','1','6','-1','4','La hache de lancer n''a plus grand-chose en commun avec la hachette des cours de ferme qui lui a donn naissance. Parfaitement quilibre pour tre lance, elle offre une grande prcision mais sa solidit en ptit.','1',0,'1','Dexterite','Hache Courte',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Hachette','Hache Courte','1','6','10','12','La hachette est plus petite que les autres haches de combat. Bien souvent, on s''en sert comme deuxime arme, dans la main non directrice.','5',0,'-1','Dexterite','Hache Courte',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Double hache','Hache Longue','12','16','80','120','On ne peut nier que la race Orque a eu un effet important sur l''art de la guerre. Le concept de la hache double vient d''une philosophie aussi simple qu''imparable : ''Si une lame bien, deux lames encore plus mieux !''','25',0,'-1','Force','Hache Longue',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Faux de combat','Hache Longue','2','4','15','36','Bien qu''elle ressemble bien videmment  l''ustensile agricole dont elle est drive, la faux de guerre a t renforce afin de ne pas se briser au premier combat.','12',0,'-1','Force','Hache Longue',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Grande hache','Hache Longue','6','12','70','40','La grande hache est l''arme de prdilection des barbares, ainsi que la plus terrible des armes drives de la hache de bcheron. Ses deux lames sont bien plus efficaces pour trancher les adversaires en deux que pour couper les arbres.','20',0,'-1','Force','Hache Longue',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Hallebarde','Hache Longue','4','10','25','20','La hallebarde est l''arme d''hast la plus courante qui soit. On pourrait la dfinir en disant qu''elle se trouve  mi-chemin de la lance et de la hache','15',0,'-1','Force','Hache Longue',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Dague','Lame Courte','1','4','30','4','Arme de base mais trs polyvalente, la dague est dote d''une lame  double tranchant faisant gnralement entre 15 et 60 centimtres de long.','1',0,'-1','Dexterite','Lame Courte',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Epe courte','Lame Courte','1','6','40','20','l''pe courte est l''une des premires pes  avoir vu le jour. Elle est dote d''une lame  double tranchant longue d''une soixantaine de centimtres','3',0,'-1','Dexterite','Lame Courte',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Kama','Lame Courte','1','6','5','4','Comme beaucoup d''armes, le kama tait  l''origine un outil de ferme, et les paysans qui ont commenc  s''en servir pour se dfendre n''avaient pour la plupart pas le droit de porter une pe ou une autre arme du mme genre.','1',0,'-1','Dexterite','Lame Courte',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Kukri','Lame Courte','2','4','30','16','Le kukri est une lourde dague  lame courbe, dont le tranchant se trouve  l''intrieur de la courbure. Il s''agissait  l''origine d''un outil, adapt depuis  un usage guerrier ou rituel.','3',0,'-1','Dexterite','Lame Courte',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Serpe','Lame Courte','1','3','10','1','A l''origine, la serpe est un outil utilis pour couper l''herbe ou les plants de crales. Ce sont les paysans qui s''en servent tous les jours qui ont commenc  l''utiliser en guise d''arme, faute de mieux.','3',0,'-1','Dexterite','Lame Courte',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Cimeterre','Lame Longue  une main','2','6','35','30','Le cimeterre serait assez proche de l''pe longue et des autres armes du mme type, si l''on excepte l''impressionnante courbure de sa large lame.','5',0,'-1','Force','Lame Longue',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Epe  2 mains','Lame Longue  2 mains','2','12','65','100','l''pe  deux mains est une arme extrmement impressionnante. Comme son nom l''indique, la plupart des cratures ne peuvent la manier qu'' deux mains.','15',0,'-1','Force','Lame Longue',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Epe btarde','Lame Longue  une main','4','10','50','70','Egalement connue sous le nom d''pe '' une main et demie'', l''pe btarde se situe dans une catgorie intermdiaire, entre l''pe longue et l''pe  deux mains','10',0,'-1','Force','Lame Longue',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Epe longue','Lame Longue  une main','3','8','60','30','Il en existe de nombreuses variantes, mais toutes sont dotes d''une lame qui fait entre 90 centimtres et 1,20 mtre de long.','4',0,'-1','Force','Lame Longue',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Katana','Lame Longue  une main','7','10','40','80','Le katana est la meilleure pe qui soit, puisqu''il combine grce, beaut et redoutable efficacit d''une lame tranchante comme un rasoir.','10',0,'-1','Dexterite','Lame Longue',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Lance','Lame Longue  une main','3','8','20','20','Arme trs simple, la lance est toutefois d''une efficacit redoutable. Elle consiste bien souvent en un long bout de bois taill en pointe et quipe la plupart des milices.','3',0,'-1','Dexterite','Lame Longue',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Bton','Masse Legere','1','6','10','2','Taill dans un bois trs rsistant et parfois dot de ferrures  ses deux extrmits, le bton est une arme que tout le monde ou presque peut apprendre  manier avec efficacit.','4',0,'-1','Dexterite','Masse Legere',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Flau d''armes lger','Masse Legere','1','8','30','16','Driv d''un ustensile de ferme servant  moudre le grain, le flau d''armes lger se compose d''une lourde tte, pointue ou non, attache par une chane  un manche en bois. Il fait une soixantaine de centimtres de long.','5',0,'-1','Dexterite','Masse Legere',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Gourdin','Masse Legere','1','6','20','2','Le gourdin est l''arme la plus simpliste qui soit, puisqu''il s''agit gnralement d''un simple bout de bois dur.','3',0,'-1','Dexterite','Masse Legere',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Marteau lger','Masse Legere','1','4','45','4','Le marteau lger est driv de l''outil du mme nom. Il reste assez lger pour que l''on s''en serve lors de fouilles, par exemple, contrairement au lourd marteau de guerre.','2',0,'-1','Dexterite','Masse Legere',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Masse d''armes','Masse Legere','2','6','20','10','La masse d''armes est un driv du gourdin. Elle est constitue d''une tte en mtal ou en pierre, fixe au bout d''un manche en bois. Le poids de la tte dcuple la puissance de l''impact.','6',0,'-1','Dexterite','Masse Legere',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Flau d''armes lourd','Masse Lourde','2','10','40','30','Driv d''un ustensile de ferme servant  moudre le grain, le flau d''armes lourd se compose d''une lourde tte, pointue ou non, attache par une chane  un manche en bois de 1,20 mtre de long.','20',0,'-1','Force','Masse Lourde',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Marteau de guerre','Masse Lourde','4','8','80','24','Lointain driv de la masse utilise dans les travaux de construction ou de terrassement, le marteau de guerre a par la suite t tellement modifi qu''il ne peut plus aujourd''hui servir qu''au combat.','8',0,'-1','Force','Masse Lourde',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Masse d''armes double','Masse Lourde','6','8','40','80','La masse d''armes double combine la facilit d''utilisation du bton et la puissance dvastatrice de la masse d''armes.','20',0,'-1','Force','Masse Lourde',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeMelee','Morgenstern','Masse Lourde','2','8','35','16','La morgenstern est une sorte de masse avec une chane, semblable au flau, pour renforcer l''impact de sa tte qui se voit dote d''une ou plusieurs pointes augmentant son efficacit.','8',0,'-1','Force','Masse Lourde',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Fronde','Petite Fronde','1','4','-1','2','La fronde est une arme trs ancienne. Bien souvent, elle se constitue d''une simple lanire en cuir ou en tissu dote d''une partie plus vase pour accueillir les projectiles.','1',0,'-1','Dexterite','Petite Fronde',null);
insert into tlt_objets (type,nom,sous_type,degats_min,degats_max ,durabilite ,prix_base,description,poids,permanent,munitions,caracteristique,competence,composantes)
values ('ArmeJet','Shuriken','Petite Fronde','1','3','-1','5','Les shurikens sont de petits projectiles faciles  dissimuler sur sa personne. Bien qu''ils ne fassent que peu de dgts individuellement, ils prsentent l''avantage de pouvoir tre lancs trs rapidement.','1',0,'10','Dexterite','Petite Fronde',null);
commit;

