version: '2'

services:
  db:
    image: mysql:5.7
    container_name: talesta4_mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: talesta4
      MYSQL_USER: talesta4
      MYSQL_PASSWORD: 6nn79WQcQ
  php:
    build: .
    container_name: talesta4
    ports:
      - 80:80
    links:
      - db:db.local