<?php
/*
Fichier de Talesta4 (cf. http://www.talesta.free.fr) version: $Name: V3_6 $  

$RCSfile: extension.inc,v $
*/

/**
Briève Description à mettre ici
.\file
$Revision: 1.4 $
$Date: 2010/01/24 19:33:12 $

*/
//
// Change this if your extension is not .php!
	$phpExtJeu = "php";  //extension des fichiers php. Laiser php si vous n'avez pas besoin de mettre php4 ou php5 pour votre hebergeur. (n'oubliez pas de renommer tous les fichiers une fois cette variable modifiée)
?>